routes/default.js
routes/v1.js
src/routers/sql-db.js
src/routers/v1/etl/garment-purchase-requests-router.js

add garment purchase request router
add sql-db

add garment purchase request router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update garment router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update garment purchase request

update garment purchase request

---

src/routers/v1/etl/garment-purchase-requests-router.js

update garment purchase request etl

update garment purchase request etl

---

src/routers/sql-db.js

sql-db update connection

---

package-lock.json
routes/default.js
routes/v1.js
src/routers/v1/purchase-order/purchase-order-by-user-router.js
src/routers/v1/purchase-order/purchase-order-router.js
src/routers/v1/report/purchase-order-report-router.js

purchase order internal report

purchase order internal report

---

src/routers/v1/purchase-order/purchase-order-router.js

update purchase order router

---

package-lock.json
package.json
routes/default.js
routes/v1.js
src/routers/v1/garment-currency/garment-currency-router.js
src/routers/v1/garment-currency/garment-currency-upload-router.js

garment currency router

---

src/routers/v1/report/purchase-order-report-router.js

add report purchase order internal by user

add report purchase order internal by user

---

src/routers/v1/garment-currency/garment-currency-upload-router.js

update garment currency router

update garment currency router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update garment purchase router

update garment purchase router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update garment etl router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update etl garment timeout

---

src/routers/v1/etl/garment-purchase-requests-router.js

update etl garment router

---

routes/v1.js
src/routers/v1/delivery-order/delivery-order-monitoring-all-router.js

add router delivery-order-monitoring-all

add router

---

src/routers/v1/etl/garment-purchase-requests-router.js

update etl router add buyer

---

routes/v1.js
src/routers/v1/generating-data/generating-data-correction-note-router.js
src/routers/v1/generating-data/generating-data-customs-router.js
src/routers/v1/generating-data/generating-data-delivery-order-router.js
src/routers/v1/generating-data/generating-data-intern-note-router.js
src/routers/v1/generating-data/generating-data-invoice-router.js
src/routers/v1/generating-data/generating-data-purchase-order-external-router.js
src/routers/v1/generating-data/generating-data-quantity-correction-note-router.js
src/routers/v1/generating-data/generating-data-unit-receipt-note-router.js

- Add Routes - Generate Data Garment Purchasing Unit Receipt Note
- Update Router  - Generate Data Garment Purchasing
- Add Router - Generate Data Garment Purchasing Unit Receipt Note

Update Routes & Router

---

src/routers/v1/purchase-order-external/purchase-order-external-by-supplier-posted-router.js

garment purchase order external by suplier posted router update

garment purchase order external by suplier posted router update

---

routes/default.js
routes/v1.js
src/routers/v1/delivery-order/delivery-order-router-basic.js

add delivery order router basic

add delivery order router basic

---

routes/default.js
routes/v1.js
src/routers/v1/purchase-order/kedatangan-router.js
src/routers/v1/purchase-order/kedatangansub-router.js

Menambah router untuk ketepatan kedatangan barang function di purchase order manager

Menambah router ketepatan kedatangan barang

---

routes/default.js
routes/v1.js
src/routers/v1/purchase-order/pengiriman-router.js
src/routers/v1/purchase-order/pengirimansub-router.js

Menambah pengiriman router dan pengirimansub router

Tambah Router Pengiriman Barang router

---

src/routers/v1/generating-data/generating-data-correction-note-router.js
src/routers/v1/generating-data/generating-data-invoice-router.js
src/routers/v1/generating-data/generating-data-quantity-correction-note-router.js

Update Router Generate Data : Invoice, Nota Koreksi Harga dan Nota Koreksi Jumlah

Update Router Generate Data Garment Pucrhasing
